/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.ChangeDomainNameserversRequest

class ChangeDomainNameserversRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChangeDomainNameserversRequest
        //val modelInstance = ChangeDomainNameserversRequest()

        // to test the property `cname`
        should("test cname") {
            // uncomment below to test the property
            //modelInstance.cname shouldBe ("TODO")
        }

        // to test the property `dnsServersOpt`
        should("test dnsServersOpt") {
            // uncomment below to test the property
            //modelInstance.dnsServersOpt shouldBe ("TODO")
        }

        // to test the property `ns`
        should("test ns") {
            // uncomment below to test the property
            //modelInstance.ns shouldBe ("TODO")
        }

        // to test the property `ns1`
        should("test ns1") {
            // uncomment below to test the property
            //modelInstance.ns1 shouldBe ("TODO")
        }

        // to test the property `ns1Ipv4`
        should("test ns1Ipv4") {
            // uncomment below to test the property
            //modelInstance.ns1Ipv4 shouldBe ("TODO")
        }

        // to test the property `ns1Ipv6`
        should("test ns1Ipv6") {
            // uncomment below to test the property
            //modelInstance.ns1Ipv6 shouldBe ("TODO")
        }

        // to test the property `ns2`
        should("test ns2") {
            // uncomment below to test the property
            //modelInstance.ns2 shouldBe ("TODO")
        }

        // to test the property `ns2Ipv4`
        should("test ns2Ipv4") {
            // uncomment below to test the property
            //modelInstance.ns2Ipv4 shouldBe ("TODO")
        }

        // to test the property `ns2Ipv6`
        should("test ns2Ipv6") {
            // uncomment below to test the property
            //modelInstance.ns2Ipv6 shouldBe ("TODO")
        }

        // to test the property `ns3`
        should("test ns3") {
            // uncomment below to test the property
            //modelInstance.ns3 shouldBe ("TODO")
        }

        // to test the property `ns3Ipv4`
        should("test ns3Ipv4") {
            // uncomment below to test the property
            //modelInstance.ns3Ipv4 shouldBe ("TODO")
        }

        // to test the property `ns3Ipv6`
        should("test ns3Ipv6") {
            // uncomment below to test the property
            //modelInstance.ns3Ipv6 shouldBe ("TODO")
        }

        // to test the property `ns4`
        should("test ns4") {
            // uncomment below to test the property
            //modelInstance.ns4 shouldBe ("TODO")
        }

        // to test the property `ns4Ipv4`
        should("test ns4Ipv4") {
            // uncomment below to test the property
            //modelInstance.ns4Ipv4 shouldBe ("TODO")
        }

        // to test the property `ns4Ipv6`
        should("test ns4Ipv6") {
            // uncomment below to test the property
            //modelInstance.ns4Ipv6 shouldBe ("TODO")
        }

    }
}
