/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.CreateCartItemRequest

class CreateCartItemRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCartItemRequest
        //val modelInstance = CreateCartItemRequest()

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `cname`
        should("test cname") {
            // uncomment below to test the property
            //modelInstance.cname shouldBe ("TODO")
        }

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `itemCount`
        should("test itemCount") {
            // uncomment below to test the property
            //modelInstance.itemCount shouldBe ("TODO")
        }

        // to test the property `currencyId`
        should("test currencyId") {
            // uncomment below to test the property
            //modelInstance.currencyId shouldBe ("TODO")
        }

        // to test the property `parameters`
        should("test parameters") {
            // uncomment below to test the property
            //modelInstance.parameters shouldBe ("TODO")
        }

        // to test the property `processType`
        should("test processType") {
            // uncomment below to test the property
            //modelInstance.processType shouldBe ("TODO")
        }

        // to test the property `lang`
        should("test lang") {
            // uncomment below to test the property
            //modelInstance.lang shouldBe ("TODO")
        }

    }
}
