/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.CreateOauthRequest200ResponseData

class CreateOauthRequest200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateOauthRequest200ResponseData
        //val modelInstance = CreateOauthRequest200ResponseData()

        // to test the property `verifyToken`
        should("test verifyToken") {
            // uncomment below to test the property
            //modelInstance.verifyToken shouldBe ("TODO")
        }

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `redirectUrl`
        should("test redirectUrl") {
            // uncomment below to test the property
            //modelInstance.redirectUrl shouldBe ("TODO")
        }

        // to test the property `verifyUrl`
        should("test verifyUrl") {
            // uncomment below to test the property
            //modelInstance.verifyUrl shouldBe ("TODO")
        }

        // to test the property `verifyIntervalSeconds`
        should("test verifyIntervalSeconds") {
            // uncomment below to test the property
            //modelInstance.verifyIntervalSeconds shouldBe ("TODO")
        }

    }
}
