/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.CreateOauthRequestRequest

class CreateOauthRequestRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateOauthRequestRequest
        //val modelInstance = CreateOauthRequestRequest()

        // to test the property `appName`
        should("test appName") {
            // uncomment below to test the property
            //modelInstance.appName shouldBe ("TODO")
        }

        // to test the property `appUrlHomepage`
        should("test appUrlHomepage") {
            // uncomment below to test the property
            //modelInstance.appUrlHomepage shouldBe ("TODO")
        }

        // to test the property `appUrlReturn`
        should("test appUrlReturn") {
            // uncomment below to test the property
            //modelInstance.appUrlReturn shouldBe ("TODO")
        }

        // to test the property `scopes`
        should("test scopes") {
            // uncomment below to test the property
            //modelInstance.scopes shouldBe ("TODO")
        }

    }
}
