/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.CreateVehicleEventRequest
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestFueling
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestLocation
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestMoney

class CreateVehicleEventRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateVehicleEventRequest
        //val modelInstance = CreateVehicleEventRequest()

        // to test the property `eventType`
        should("test eventType") {
            // uncomment below to test the property
            //modelInstance.eventType shouldBe ("TODO")
        }

        // to test the property `datetimeLocal`
        should("test datetimeLocal") {
            // uncomment below to test the property
            //modelInstance.datetimeLocal shouldBe ("TODO")
        }

        // to test the property `timezone`
        should("test timezone") {
            // uncomment below to test the property
            //modelInstance.timezone shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `vehicleId`
        should("test vehicleId") {
            // uncomment below to test the property
            //modelInstance.vehicleId shouldBe ("TODO")
        }

        // to test the property `purpose`
        should("test purpose") {
            // uncomment below to test the property
            //modelInstance.purpose shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `odometer`
        should("test odometer") {
            // uncomment below to test the property
            //modelInstance.odometer shouldBe ("TODO")
        }

        // to test the property `money`
        should("test money") {
            // uncomment below to test the property
            //modelInstance.money shouldBe ("TODO")
        }

        // to test the property `fueling`
        should("test fueling") {
            // uncomment below to test the property
            //modelInstance.fueling shouldBe ("TODO")
        }

    }
}
