/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.CreateDnsRecordRequest

class CreateDnsRecordRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateDnsRecordRequest
        //val modelInstance = CreateDnsRecordRequest()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `ttl`
        should("test ttl") {
            // uncomment below to test the property
            //modelInstance.ttl shouldBe ("TODO")
        }

        // to test the property `prio`
        should("test prio") {
            // uncomment below to test the property
            //modelInstance.prio shouldBe ("TODO")
        }

    }
}
