/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestLocation

class FinalizeVehicleEventRequestLocationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FinalizeVehicleEventRequestLocation
        //val modelInstance = FinalizeVehicleEventRequestLocation()

        // to test the property `addressText`
        should("test addressText") {
            // uncomment below to test the property
            //modelInstance.addressText shouldBe ("TODO")
        }

        // to test the property `lat`
        should("test lat") {
            // uncomment below to test the property
            //modelInstance.lat shouldBe ("TODO")
        }

        // to test the property `lon`
        should("test lon") {
            // uncomment below to test the property
            //modelInstance.lon shouldBe ("TODO")
        }

        // to test the property `placeName`
        should("test placeName") {
            // uncomment below to test the property
            //modelInstance.placeName shouldBe ("TODO")
        }

    }
}
