/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestFueling

class FinalizeVehicleEventRequestFuelingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FinalizeVehicleEventRequestFueling
        //val modelInstance = FinalizeVehicleEventRequestFueling()

        // to test the property `fuelingNo`
        should("test fuelingNo") {
            // uncomment below to test the property
            //modelInstance.fuelingNo shouldBe ("TODO")
        }

        // to test the property `fuelType`
        should("test fuelType") {
            // uncomment below to test the property
            //modelInstance.fuelType shouldBe ("TODO")
        }

        // to test the property `volume`
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

        // to test the property `unit`
        should("test unit") {
            // uncomment below to test the property
            //modelInstance.unit shouldBe ("TODO")
        }

    }
}
