/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.GetDnsRecords200ResponseData
import sk.platon.controlpanel.sdk.models.GetDnsRecords200ResponseDataRecordsInner

class GetDnsRecords200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDnsRecords200ResponseData
        //val modelInstance = GetDnsRecords200ResponseData()

        // to test the property `domainId`
        should("test domainId") {
            // uncomment below to test the property
            //modelInstance.domainId shouldBe ("TODO")
        }

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `master`
        should("test master") {
            // uncomment below to test the property
            //modelInstance.master shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `records`
        should("test records") {
            // uncomment below to test the property
            //modelInstance.records shouldBe ("TODO")
        }

    }
}
