/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.MergeCartItems200ResponseData

class MergeCartItems200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MergeCartItems200ResponseData
        //val modelInstance = MergeCartItems200ResponseData()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `merged`
        should("test merged") {
            // uncomment below to test the property
            //modelInstance.merged shouldBe ("TODO")
        }

        // to test the property `fromCname`
        should("test fromCname") {
            // uncomment below to test the property
            //modelInstance.fromCname shouldBe ("TODO")
        }

        // to test the property `toCname`
        should("test toCname") {
            // uncomment below to test the property
            //modelInstance.toCname shouldBe ("TODO")
        }

        // to test the property `movedItems`
        should("test movedItems") {
            // uncomment below to test the property
            //modelInstance.movedItems shouldBe ("TODO")
        }

        // to test the property `mergedItems`
        should("test mergedItems") {
            // uncomment below to test the property
            //modelInstance.mergedItems shouldBe ("TODO")
        }

        // to test the property `itemsCount`
        should("test itemsCount") {
            // uncomment below to test the property
            //modelInstance.itemsCount shouldBe ("TODO")
        }

    }
}
