/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.RenewDomainRequest

class RenewDomainRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RenewDomainRequest
        //val modelInstance = RenewDomainRequest()

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

    }
}
