/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.Revision200ResponseData

class Revision200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Revision200ResponseData
        //val modelInstance = Revision200ResponseData()

        // to test the property `revision`
        should("test revision") {
            // uncomment below to test the property
            //modelInstance.revision shouldBe ("TODO")
        }

    }
}
