/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.SpamDetection200ResponseData

class SpamDetection200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpamDetection200ResponseData
        //val modelInstance = SpamDetection200ResponseData()

        // to test the property `classification` - Normalized classification returned by the LLM.
        should("test classification") {
            // uncomment below to test the property
            //modelInstance.classification shouldBe ("TODO")
        }

        // to test the property `confidence` - Normalized confidence from 0 to 100.
        should("test confidence") {
            // uncomment below to test the property
            //modelInstance.confidence shouldBe ("TODO")
        }

        // to test the property `reason` - Short explanation in Slovak.
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

        // to test the property `signals` - Most important signals used for the classification.
        should("test signals") {
            // uncomment below to test the property
            //modelInstance.signals shouldBe ("TODO")
        }

        // to test the property `error` - True when the LLM call or response validation failed.
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `errorMessage` - Short technical error reason. Raw LLM response is never returned here.
        should("test errorMessage") {
            // uncomment below to test the property
            //modelInstance.errorMessage shouldBe ("TODO")
        }

    }
}
