/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.UpdateCartItemRequest
import sk.platon.controlpanel.sdk.models.UpdateCartItemRequestData

class UpdateCartItemRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateCartItemRequest
        //val modelInstance = UpdateCartItemRequest()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `cname`
        should("test cname") {
            // uncomment below to test the property
            //modelInstance.cname shouldBe ("TODO")
        }

    }
}
