/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.UpdateCartItemRequestData

class UpdateCartItemRequestDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateCartItemRequestData
        //val modelInstance = UpdateCartItemRequestData()

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `productDetail`
        should("test productDetail") {
            // uncomment below to test the property
            //modelInstance.productDetail shouldBe ("TODO")
        }

        // to test the property `itemCount`
        should("test itemCount") {
            // uncomment below to test the property
            //modelInstance.itemCount shouldBe ("TODO")
        }

        // to test the property `price`
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `productPrice`
        should("test productPrice") {
            // uncomment below to test the property
            //modelInstance.productPrice shouldBe ("TODO")
        }

    }
}
