/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.VerifyOauthRequest200ResponseData

class VerifyOauthRequest200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VerifyOauthRequest200ResponseData
        //val modelInstance = VerifyOauthRequest200ResponseData()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `token`
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `tokenExpire`
        should("test tokenExpire") {
            // uncomment below to test the property
            //modelInstance.tokenExpire shouldBe ("TODO")
        }

        // to test the property `cname`
        should("test cname") {
            // uncomment below to test the property
            //modelInstance.cname shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
