/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.models.WhoisDomain200ResponseData
import sk.platon.controlpanel.sdk.models.WhoisDomain200ResponseDataRetval

class WhoisDomain200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WhoisDomain200ResponseData
        //val modelInstance = WhoisDomain200ResponseData()

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `isFree`
        should("test isFree") {
            // uncomment below to test the property
            //modelInstance.isFree shouldBe ("TODO")
        }

        // to test the property `isPremium`
        should("test isPremium") {
            // uncomment below to test the property
            //modelInstance.isPremium shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `retval`
        should("test retval") {
            // uncomment below to test the property
            //modelInstance.retval shouldBe ("TODO")
        }

        // to test the property `prices`
        should("test prices") {
            // uncomment below to test the property
            //modelInstance.prices shouldBe ("TODO")
        }

    }
}
