/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.AddAntispamMaildataRequest
import sk.platon.controlpanel.sdk.models.CheckAntispamMaildataRulesRequest
import sk.platon.controlpanel.sdk.models.CreateAntispamEmailRuleRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class AntispamApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * POST /antispam/maildata
     * Add maildata to antispam engine
     * 
     * @param addAntispamMaildataRequest Maildata payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun addAntispamMaildata(addAntispamMaildataRequest: AddAntispamMaildataRequest) : CreateDnsRecord200Response {
        val localVarResponse = addAntispamMaildataWithHttpInfo(addAntispamMaildataRequest = addAntispamMaildataRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /antispam/maildata
     * Add maildata to antispam engine
     * 
     * @param addAntispamMaildataRequest Maildata payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun addAntispamMaildataWithHttpInfo(addAntispamMaildataRequest: AddAntispamMaildataRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = addAntispamMaildataRequestConfig(addAntispamMaildataRequest = addAntispamMaildataRequest)

        return request<AddAntispamMaildataRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation addAntispamMaildata
     *
     * @param addAntispamMaildataRequest Maildata payload
     * @return RequestConfig
     */
    fun addAntispamMaildataRequestConfig(addAntispamMaildataRequest: AddAntispamMaildataRequest) : RequestConfig<AddAntispamMaildataRequest> {
        val localVariableBody = addAntispamMaildataRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/antispam/maildata",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /antispam/maildata/check
     * Check maildata against existing antispam rules
     * 
     * @param checkAntispamMaildataRulesRequest Maildata payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun checkAntispamMaildataRules(checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest) : CreateDnsRecord200Response {
        val localVarResponse = checkAntispamMaildataRulesWithHttpInfo(checkAntispamMaildataRulesRequest = checkAntispamMaildataRulesRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /antispam/maildata/check
     * Check maildata against existing antispam rules
     * 
     * @param checkAntispamMaildataRulesRequest Maildata payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun checkAntispamMaildataRulesWithHttpInfo(checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = checkAntispamMaildataRulesRequestConfig(checkAntispamMaildataRulesRequest = checkAntispamMaildataRulesRequest)

        return request<CheckAntispamMaildataRulesRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation checkAntispamMaildataRules
     *
     * @param checkAntispamMaildataRulesRequest Maildata payload
     * @return RequestConfig
     */
    fun checkAntispamMaildataRulesRequestConfig(checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest) : RequestConfig<CheckAntispamMaildataRulesRequest> {
        val localVariableBody = checkAntispamMaildataRulesRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/antispam/maildata/check",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /antispam/rules
     * Create antispam email rule or increment existing rule hitcount
     * 
     * @param createAntispamEmailRuleRequest Antispam email rule payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createAntispamEmailRule(createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest) : CreateDnsRecord200Response {
        val localVarResponse = createAntispamEmailRuleWithHttpInfo(createAntispamEmailRuleRequest = createAntispamEmailRuleRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /antispam/rules
     * Create antispam email rule or increment existing rule hitcount
     * 
     * @param createAntispamEmailRuleRequest Antispam email rule payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createAntispamEmailRuleWithHttpInfo(createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = createAntispamEmailRuleRequestConfig(createAntispamEmailRuleRequest = createAntispamEmailRuleRequest)

        return request<CreateAntispamEmailRuleRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createAntispamEmailRule
     *
     * @param createAntispamEmailRuleRequest Antispam email rule payload
     * @return RequestConfig
     */
    fun createAntispamEmailRuleRequestConfig(createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest) : RequestConfig<CreateAntispamEmailRuleRequest> {
        val localVariableBody = createAntispamEmailRuleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/antispam/rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
