/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.CheckCartCouponRequest
import sk.platon.controlpanel.sdk.models.CreateCartItemRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.MergeCartItems200Response
import sk.platon.controlpanel.sdk.models.MergeCartItemsRequest
import sk.platon.controlpanel.sdk.models.UpdateCartItemCountRequest
import sk.platon.controlpanel.sdk.models.UpdateCartItemRequest

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class CartApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * POST /cart/coupons/check
     * Check and apply cart coupon
     * 
     * @param checkCartCouponRequest Cart coupon check payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun checkCartCoupon(checkCartCouponRequest: CheckCartCouponRequest) : CreateDnsRecord200Response {
        val localVarResponse = checkCartCouponWithHttpInfo(checkCartCouponRequest = checkCartCouponRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cart/coupons/check
     * Check and apply cart coupon
     * 
     * @param checkCartCouponRequest Cart coupon check payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun checkCartCouponWithHttpInfo(checkCartCouponRequest: CheckCartCouponRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = checkCartCouponRequestConfig(checkCartCouponRequest = checkCartCouponRequest)

        return request<CheckCartCouponRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation checkCartCoupon
     *
     * @param checkCartCouponRequest Cart coupon check payload
     * @return RequestConfig
     */
    fun checkCartCouponRequestConfig(checkCartCouponRequest: CheckCartCouponRequest) : RequestConfig<CheckCartCouponRequest> {
        val localVariableBody = checkCartCouponRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cart/coupons/check",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cart/items
     * Add item to cart
     * 
     * @param createCartItemRequest Cart item add payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createCartItem(createCartItemRequest: CreateCartItemRequest) : CreateDnsRecord200Response {
        val localVarResponse = createCartItemWithHttpInfo(createCartItemRequest = createCartItemRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cart/items
     * Add item to cart
     * 
     * @param createCartItemRequest Cart item add payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createCartItemWithHttpInfo(createCartItemRequest: CreateCartItemRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = createCartItemRequestConfig(createCartItemRequest = createCartItemRequest)

        return request<CreateCartItemRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createCartItem
     *
     * @param createCartItemRequest Cart item add payload
     * @return RequestConfig
     */
    fun createCartItemRequestConfig(createCartItemRequest: CreateCartItemRequest) : RequestConfig<CreateCartItemRequest> {
        val localVariableBody = createCartItemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cart/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /cart/items/{cartItemId}
     * Remove item from cart
     * 
     * @param cartItemId Cart item ID
     * @param cname Customer name (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteCartItem(cartItemId: kotlin.Int, cname: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = deleteCartItemWithHttpInfo(cartItemId = cartItemId, cname = cname)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /cart/items/{cartItemId}
     * Remove item from cart
     * 
     * @param cartItemId Cart item ID
     * @param cname Customer name (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteCartItemWithHttpInfo(cartItemId: kotlin.Int, cname: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = deleteCartItemRequestConfig(cartItemId = cartItemId, cname = cname)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteCartItem
     *
     * @param cartItemId Cart item ID
     * @param cname Customer name (optional)
     * @return RequestConfig
     */
    fun deleteCartItemRequestConfig(cartItemId: kotlin.Int, cname: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cname != null) {
                    put("cname", listOf(cname.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/cart/items/{cartItemId}".replace("{"+"cartItemId"+"}", encodeURIComponent(cartItemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cart/billing-address
     * Get cart billing address
     * 
     * @param cname Customer name (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCartBillingAddress(cname: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = getCartBillingAddressWithHttpInfo(cname = cname)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cart/billing-address
     * Get cart billing address
     * 
     * @param cname Customer name (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCartBillingAddressWithHttpInfo(cname: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = getCartBillingAddressRequestConfig(cname = cname)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCartBillingAddress
     *
     * @param cname Customer name (optional)
     * @return RequestConfig
     */
    fun getCartBillingAddressRequestConfig(cname: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cname != null) {
                    put("cname", listOf(cname.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cart/billing-address",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cart/coupons/current
     * Get current cart coupon
     * 
     * @param cname Customer name (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCartCoupon(cname: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = getCartCouponWithHttpInfo(cname = cname)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cart/coupons/current
     * Get current cart coupon
     * 
     * @param cname Customer name (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCartCouponWithHttpInfo(cname: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = getCartCouponRequestConfig(cname = cname)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCartCoupon
     *
     * @param cname Customer name (optional)
     * @return RequestConfig
     */
    fun getCartCouponRequestConfig(cname: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cname != null) {
                    put("cname", listOf(cname.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cart/coupons/current",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cart/total
     * Get cart total
     * 
     * @param cname Customer name (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCartTotal(cname: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = getCartTotalWithHttpInfo(cname = cname)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cart/total
     * Get cart total
     * 
     * @param cname Customer name (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCartTotalWithHttpInfo(cname: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = getCartTotalRequestConfig(cname = cname)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCartTotal
     *
     * @param cname Customer name (optional)
     * @return RequestConfig
     */
    fun getCartTotalRequestConfig(cname: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cname != null) {
                    put("cname", listOf(cname.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cart/total",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /cart/items
     * List cart items
     * 
     * @param cname Customer name (optional)
     * @param lang Response language (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listCartItems(cname: kotlin.String? = null, lang: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = listCartItemsWithHttpInfo(cname = cname, lang = lang)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /cart/items
     * List cart items
     * 
     * @param cname Customer name (optional)
     * @param lang Response language (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listCartItemsWithHttpInfo(cname: kotlin.String?, lang: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = listCartItemsRequestConfig(cname = cname, lang = lang)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCartItems
     *
     * @param cname Customer name (optional)
     * @param lang Response language (optional)
     * @return RequestConfig
     */
    fun listCartItemsRequestConfig(cname: kotlin.String?, lang: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cname != null) {
                    put("cname", listOf(cname.toString()))
                }
                if (lang != null) {
                    put("lang", listOf(lang.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/cart/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /cart/items/merge
     * Merge anonymous cart items into current customer cart
     * 
     * @param mergeCartItemsRequest Anonymous cart merge payload
     * @return MergeCartItems200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun mergeCartItems(mergeCartItemsRequest: MergeCartItemsRequest) : MergeCartItems200Response {
        val localVarResponse = mergeCartItemsWithHttpInfo(mergeCartItemsRequest = mergeCartItemsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MergeCartItems200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /cart/items/merge
     * Merge anonymous cart items into current customer cart
     * 
     * @param mergeCartItemsRequest Anonymous cart merge payload
     * @return ApiResponse<MergeCartItems200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun mergeCartItemsWithHttpInfo(mergeCartItemsRequest: MergeCartItemsRequest) : ApiResponse<MergeCartItems200Response?> {
        val localVariableConfig = mergeCartItemsRequestConfig(mergeCartItemsRequest = mergeCartItemsRequest)

        return request<MergeCartItemsRequest, MergeCartItems200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation mergeCartItems
     *
     * @param mergeCartItemsRequest Anonymous cart merge payload
     * @return RequestConfig
     */
    fun mergeCartItemsRequestConfig(mergeCartItemsRequest: MergeCartItemsRequest) : RequestConfig<MergeCartItemsRequest> {
        val localVariableBody = mergeCartItemsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/cart/items/merge",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /cart/items/{cartItemId}
     * Update cart item data
     * 
     * @param cartItemId Cart item ID
     * @param updateCartItemRequest Cart item update payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateCartItem(cartItemId: kotlin.Int, updateCartItemRequest: UpdateCartItemRequest) : CreateDnsRecord200Response {
        val localVarResponse = updateCartItemWithHttpInfo(cartItemId = cartItemId, updateCartItemRequest = updateCartItemRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /cart/items/{cartItemId}
     * Update cart item data
     * 
     * @param cartItemId Cart item ID
     * @param updateCartItemRequest Cart item update payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateCartItemWithHttpInfo(cartItemId: kotlin.Int, updateCartItemRequest: UpdateCartItemRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = updateCartItemRequestConfig(cartItemId = cartItemId, updateCartItemRequest = updateCartItemRequest)

        return request<UpdateCartItemRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateCartItem
     *
     * @param cartItemId Cart item ID
     * @param updateCartItemRequest Cart item update payload
     * @return RequestConfig
     */
    fun updateCartItemRequestConfig(cartItemId: kotlin.Int, updateCartItemRequest: UpdateCartItemRequest) : RequestConfig<UpdateCartItemRequest> {
        val localVariableBody = updateCartItemRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/cart/items/{cartItemId}".replace("{"+"cartItemId"+"}", encodeURIComponent(cartItemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /cart/items/by-product/count
     * Update cart item count by product and domain
     * 
     * @param updateCartItemCountRequest Cart item count update payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateCartItemCount(updateCartItemCountRequest: UpdateCartItemCountRequest) : CreateDnsRecord200Response {
        val localVarResponse = updateCartItemCountWithHttpInfo(updateCartItemCountRequest = updateCartItemCountRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /cart/items/by-product/count
     * Update cart item count by product and domain
     * 
     * @param updateCartItemCountRequest Cart item count update payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateCartItemCountWithHttpInfo(updateCartItemCountRequest: UpdateCartItemCountRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = updateCartItemCountRequestConfig(updateCartItemCountRequest = updateCartItemCountRequest)

        return request<UpdateCartItemCountRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateCartItemCount
     *
     * @param updateCartItemCountRequest Cart item count update payload
     * @return RequestConfig
     */
    fun updateCartItemCountRequestConfig(updateCartItemCountRequest: UpdateCartItemCountRequest) : RequestConfig<UpdateCartItemCountRequest> {
        val localVariableBody = updateCartItemCountRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/cart/items/by-product/count",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
