/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.CreateDnsRecordRequest
import sk.platon.controlpanel.sdk.models.GetDnsRecords200Response
import sk.platon.controlpanel.sdk.models.UpdateDnsRecordRequest

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class DNSApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * POST /dns/{domain}/records
     * Create DNS record
     * 
     * @param domain Domain name
     * @param createDnsRecordRequest DNS record payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createDnsRecord(domain: kotlin.String, createDnsRecordRequest: CreateDnsRecordRequest) : CreateDnsRecord200Response {
        val localVarResponse = createDnsRecordWithHttpInfo(domain = domain, createDnsRecordRequest = createDnsRecordRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /dns/{domain}/records
     * Create DNS record
     * 
     * @param domain Domain name
     * @param createDnsRecordRequest DNS record payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createDnsRecordWithHttpInfo(domain: kotlin.String, createDnsRecordRequest: CreateDnsRecordRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = createDnsRecordRequestConfig(domain = domain, createDnsRecordRequest = createDnsRecordRequest)

        return request<CreateDnsRecordRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createDnsRecord
     *
     * @param domain Domain name
     * @param createDnsRecordRequest DNS record payload
     * @return RequestConfig
     */
    fun createDnsRecordRequestConfig(domain: kotlin.String, createDnsRecordRequest: CreateDnsRecordRequest) : RequestConfig<CreateDnsRecordRequest> {
        val localVariableBody = createDnsRecordRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dns/{domain}/records".replace("{"+"domain"+"}", encodeURIComponent(domain.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /dns/{domain}/records/{recordId}
     * Delete DNS record
     * 
     * @param domain Domain name
     * @param recordId Record ID
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteDnsRecord(domain: kotlin.String, recordId: kotlin.Int) : CreateDnsRecord200Response {
        val localVarResponse = deleteDnsRecordWithHttpInfo(domain = domain, recordId = recordId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /dns/{domain}/records/{recordId}
     * Delete DNS record
     * 
     * @param domain Domain name
     * @param recordId Record ID
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteDnsRecordWithHttpInfo(domain: kotlin.String, recordId: kotlin.Int) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = deleteDnsRecordRequestConfig(domain = domain, recordId = recordId)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteDnsRecord
     *
     * @param domain Domain name
     * @param recordId Record ID
     * @return RequestConfig
     */
    fun deleteDnsRecordRequestConfig(domain: kotlin.String, recordId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/dns/{domain}/records/{recordId}".replace("{"+"domain"+"}", encodeURIComponent(domain.toString())).replace("{"+"recordId"+"}", encodeURIComponent(recordId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /dns/{domain}/records
     * Get DNS records by domain
     * 
     * @param domain Domain name
     * @param type Filter records by type (optional)
     * @return GetDnsRecords200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getDnsRecords(domain: kotlin.String, type: kotlin.String? = null) : GetDnsRecords200Response {
        val localVarResponse = getDnsRecordsWithHttpInfo(domain = domain, type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetDnsRecords200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dns/{domain}/records
     * Get DNS records by domain
     * 
     * @param domain Domain name
     * @param type Filter records by type (optional)
     * @return ApiResponse<GetDnsRecords200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getDnsRecordsWithHttpInfo(domain: kotlin.String, type: kotlin.String?) : ApiResponse<GetDnsRecords200Response?> {
        val localVariableConfig = getDnsRecordsRequestConfig(domain = domain, type = type)

        return request<Unit, GetDnsRecords200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getDnsRecords
     *
     * @param domain Domain name
     * @param type Filter records by type (optional)
     * @return RequestConfig
     */
    fun getDnsRecordsRequestConfig(domain: kotlin.String, type: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dns/{domain}/records".replace("{"+"domain"+"}", encodeURIComponent(domain.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /dns/{domain}/records/{recordId}
     * Update DNS record
     * 
     * @param domain Domain name
     * @param recordId Record ID
     * @param updateDnsRecordRequest Partial DNS record payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateDnsRecord(domain: kotlin.String, recordId: kotlin.Int, updateDnsRecordRequest: UpdateDnsRecordRequest) : CreateDnsRecord200Response {
        val localVarResponse = updateDnsRecordWithHttpInfo(domain = domain, recordId = recordId, updateDnsRecordRequest = updateDnsRecordRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /dns/{domain}/records/{recordId}
     * Update DNS record
     * 
     * @param domain Domain name
     * @param recordId Record ID
     * @param updateDnsRecordRequest Partial DNS record payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateDnsRecordWithHttpInfo(domain: kotlin.String, recordId: kotlin.Int, updateDnsRecordRequest: UpdateDnsRecordRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = updateDnsRecordRequestConfig(domain = domain, recordId = recordId, updateDnsRecordRequest = updateDnsRecordRequest)

        return request<UpdateDnsRecordRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateDnsRecord
     *
     * @param domain Domain name
     * @param recordId Record ID
     * @param updateDnsRecordRequest Partial DNS record payload
     * @return RequestConfig
     */
    fun updateDnsRecordRequestConfig(domain: kotlin.String, recordId: kotlin.Int, updateDnsRecordRequest: UpdateDnsRecordRequest) : RequestConfig<UpdateDnsRecordRequest> {
        val localVariableBody = updateDnsRecordRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/dns/{domain}/records/{recordId}".replace("{"+"domain"+"}", encodeURIComponent(domain.toString())).replace("{"+"recordId"+"}", encodeURIComponent(recordId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
