/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.ChangeMailboxPasswordRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.CreateMailboxRequest

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class EmailApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * PATCH /email/{domain}/mailboxes/{username}/password
     * Change mailbox password
     * 
     * @param domain Domain name
     * @param username Mailbox username
     * @param changeMailboxPasswordRequest Mailbox password payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun changeMailboxPassword(domain: kotlin.String, username: kotlin.String, changeMailboxPasswordRequest: ChangeMailboxPasswordRequest) : CreateDnsRecord200Response {
        val localVarResponse = changeMailboxPasswordWithHttpInfo(domain = domain, username = username, changeMailboxPasswordRequest = changeMailboxPasswordRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /email/{domain}/mailboxes/{username}/password
     * Change mailbox password
     * 
     * @param domain Domain name
     * @param username Mailbox username
     * @param changeMailboxPasswordRequest Mailbox password payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun changeMailboxPasswordWithHttpInfo(domain: kotlin.String, username: kotlin.String, changeMailboxPasswordRequest: ChangeMailboxPasswordRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = changeMailboxPasswordRequestConfig(domain = domain, username = username, changeMailboxPasswordRequest = changeMailboxPasswordRequest)

        return request<ChangeMailboxPasswordRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation changeMailboxPassword
     *
     * @param domain Domain name
     * @param username Mailbox username
     * @param changeMailboxPasswordRequest Mailbox password payload
     * @return RequestConfig
     */
    fun changeMailboxPasswordRequestConfig(domain: kotlin.String, username: kotlin.String, changeMailboxPasswordRequest: ChangeMailboxPasswordRequest) : RequestConfig<ChangeMailboxPasswordRequest> {
        val localVariableBody = changeMailboxPasswordRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/email/{domain}/mailboxes/{username}/password".replace("{"+"domain"+"}", encodeURIComponent(domain.toString())).replace("{"+"username"+"}", encodeURIComponent(username.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /email/{domain}/mailboxes
     * Create mailbox
     * 
     * @param domain Domain name
     * @param createMailboxRequest Mailbox payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createMailbox(domain: kotlin.String, createMailboxRequest: CreateMailboxRequest) : CreateDnsRecord200Response {
        val localVarResponse = createMailboxWithHttpInfo(domain = domain, createMailboxRequest = createMailboxRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /email/{domain}/mailboxes
     * Create mailbox
     * 
     * @param domain Domain name
     * @param createMailboxRequest Mailbox payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createMailboxWithHttpInfo(domain: kotlin.String, createMailboxRequest: CreateMailboxRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = createMailboxRequestConfig(domain = domain, createMailboxRequest = createMailboxRequest)

        return request<CreateMailboxRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createMailbox
     *
     * @param domain Domain name
     * @param createMailboxRequest Mailbox payload
     * @return RequestConfig
     */
    fun createMailboxRequestConfig(domain: kotlin.String, createMailboxRequest: CreateMailboxRequest) : RequestConfig<CreateMailboxRequest> {
        val localVariableBody = createMailboxRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/email/{domain}/mailboxes".replace("{"+"domain"+"}", encodeURIComponent(domain.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
