/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.SpamDetection200Response
import sk.platon.controlpanel.sdk.models.SpamDetectionRequest

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class LLMApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * POST /llm/spam-detection
     * Classify a web form message as spam or ham using the local LLM
     * 
     * @param spamDetectionRequest Spam detection payload
     * @return SpamDetection200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun spamDetection(spamDetectionRequest: SpamDetectionRequest) : SpamDetection200Response {
        val localVarResponse = spamDetectionWithHttpInfo(spamDetectionRequest = spamDetectionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SpamDetection200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /llm/spam-detection
     * Classify a web form message as spam or ham using the local LLM
     * 
     * @param spamDetectionRequest Spam detection payload
     * @return ApiResponse<SpamDetection200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun spamDetectionWithHttpInfo(spamDetectionRequest: SpamDetectionRequest) : ApiResponse<SpamDetection200Response?> {
        val localVariableConfig = spamDetectionRequestConfig(spamDetectionRequest = spamDetectionRequest)

        return request<SpamDetectionRequest, SpamDetection200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation spamDetection
     *
     * @param spamDetectionRequest Spam detection payload
     * @return RequestConfig
     */
    fun spamDetectionRequestConfig(spamDetectionRequest: SpamDetectionRequest) : RequestConfig<SpamDetectionRequest> {
        val localVariableBody = spamDetectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/llm/spam-detection",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
