/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.CreateOauthRequest200Response
import sk.platon.controlpanel.sdk.models.CreateOauthRequestRequest
import sk.platon.controlpanel.sdk.models.DeleteOauthToken200Response
import sk.platon.controlpanel.sdk.models.GetOauthScopes200Response
import sk.platon.controlpanel.sdk.models.RefreshOauthTokenRequest
import sk.platon.controlpanel.sdk.models.VerifyOauthRequest200Response

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class OAuthApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * POST /oauth/requests
     * Create OAuth request
     * 
     * @param createOauthRequestRequest OAuth create payload (optional)
     * @return CreateOauthRequest200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createOauthRequest(createOauthRequestRequest: CreateOauthRequestRequest? = null) : CreateOauthRequest200Response {
        val localVarResponse = createOauthRequestWithHttpInfo(createOauthRequestRequest = createOauthRequestRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateOauthRequest200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /oauth/requests
     * Create OAuth request
     * 
     * @param createOauthRequestRequest OAuth create payload (optional)
     * @return ApiResponse<CreateOauthRequest200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createOauthRequestWithHttpInfo(createOauthRequestRequest: CreateOauthRequestRequest?) : ApiResponse<CreateOauthRequest200Response?> {
        val localVariableConfig = createOauthRequestRequestConfig(createOauthRequestRequest = createOauthRequestRequest)

        return request<CreateOauthRequestRequest, CreateOauthRequest200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createOauthRequest
     *
     * @param createOauthRequestRequest OAuth create payload (optional)
     * @return RequestConfig
     */
    fun createOauthRequestRequestConfig(createOauthRequestRequest: CreateOauthRequestRequest?) : RequestConfig<CreateOauthRequestRequest> {
        val localVariableBody = createOauthRequestRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/oauth/requests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * DELETE /oauth/tokens
     * Delete OAuth token
     * 
     * @param token OAuth token
     * @return DeleteOauthToken200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteOauthToken(token: kotlin.String) : DeleteOauthToken200Response {
        val localVarResponse = deleteOauthTokenWithHttpInfo(token = token)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeleteOauthToken200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /oauth/tokens
     * Delete OAuth token
     * 
     * @param token OAuth token
     * @return ApiResponse<DeleteOauthToken200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteOauthTokenWithHttpInfo(token: kotlin.String) : ApiResponse<DeleteOauthToken200Response?> {
        val localVariableConfig = deleteOauthTokenRequestConfig(token = token)

        return request<Unit, DeleteOauthToken200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteOauthToken
     *
     * @param token OAuth token
     * @return RequestConfig
     */
    fun deleteOauthTokenRequestConfig(token: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("token", listOf(token.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/oauth/tokens",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /oauth/scopes
     * List available OAuth scopes
     * 
     * @return GetOauthScopes200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getOauthScopes() : GetOauthScopes200Response {
        val localVarResponse = getOauthScopesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetOauthScopes200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /oauth/scopes
     * List available OAuth scopes
     * 
     * @return ApiResponse<GetOauthScopes200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getOauthScopesWithHttpInfo() : ApiResponse<GetOauthScopes200Response?> {
        val localVariableConfig = getOauthScopesRequestConfig()

        return request<Unit, GetOauthScopes200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getOauthScopes
     *
     * @return RequestConfig
     */
    fun getOauthScopesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/oauth/scopes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /oauth/tokens/refresh
     * Refresh OAuth token
     * 
     * @param refreshOauthTokenRequest OAuth refresh payload
     * @return VerifyOauthRequest200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refreshOauthToken(refreshOauthTokenRequest: RefreshOauthTokenRequest) : VerifyOauthRequest200Response {
        val localVarResponse = refreshOauthTokenWithHttpInfo(refreshOauthTokenRequest = refreshOauthTokenRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as VerifyOauthRequest200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /oauth/tokens/refresh
     * Refresh OAuth token
     * 
     * @param refreshOauthTokenRequest OAuth refresh payload
     * @return ApiResponse<VerifyOauthRequest200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun refreshOauthTokenWithHttpInfo(refreshOauthTokenRequest: RefreshOauthTokenRequest) : ApiResponse<VerifyOauthRequest200Response?> {
        val localVariableConfig = refreshOauthTokenRequestConfig(refreshOauthTokenRequest = refreshOauthTokenRequest)

        return request<RefreshOauthTokenRequest, VerifyOauthRequest200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refreshOauthToken
     *
     * @param refreshOauthTokenRequest OAuth refresh payload
     * @return RequestConfig
     */
    fun refreshOauthTokenRequestConfig(refreshOauthTokenRequest: RefreshOauthTokenRequest) : RequestConfig<RefreshOauthTokenRequest> {
        val localVariableBody = refreshOauthTokenRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/oauth/tokens/refresh",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /oauth/requests/verify
     * Verify OAuth request
     * 
     * @param verifyToken Verify token from OAuth create response
     * @return VerifyOauthRequest200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun verifyOauthRequest(verifyToken: kotlin.String) : VerifyOauthRequest200Response {
        val localVarResponse = verifyOauthRequestWithHttpInfo(verifyToken = verifyToken)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as VerifyOauthRequest200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /oauth/requests/verify
     * Verify OAuth request
     * 
     * @param verifyToken Verify token from OAuth create response
     * @return ApiResponse<VerifyOauthRequest200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun verifyOauthRequestWithHttpInfo(verifyToken: kotlin.String) : ApiResponse<VerifyOauthRequest200Response?> {
        val localVariableConfig = verifyOauthRequestRequestConfig(verifyToken = verifyToken)

        return request<Unit, VerifyOauthRequest200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation verifyOauthRequest
     *
     * @param verifyToken Verify token from OAuth create response
     * @return RequestConfig
     */
    fun verifyOauthRequestRequestConfig(verifyToken: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("verify_token", listOf(verifyToken.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/oauth/requests/verify",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
