/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.CreateVehicleEventRequest
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequest
import sk.platon.controlpanel.sdk.models.SetPreferredVehicleRequest

import com.squareup.moshi.Json

import sk.platon.controlpanel.sdk.infrastructure.ApiClient
import sk.platon.controlpanel.sdk.infrastructure.ApiResponse
import sk.platon.controlpanel.sdk.infrastructure.ClientException
import sk.platon.controlpanel.sdk.infrastructure.ClientError
import sk.platon.controlpanel.sdk.infrastructure.ServerException
import sk.platon.controlpanel.sdk.infrastructure.ServerError
import sk.platon.controlpanel.sdk.infrastructure.MultiValueMap
import sk.platon.controlpanel.sdk.infrastructure.PartConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestConfig
import sk.platon.controlpanel.sdk.infrastructure.RequestMethod
import sk.platon.controlpanel.sdk.infrastructure.ResponseType
import sk.platon.controlpanel.sdk.infrastructure.Success
import sk.platon.controlpanel.sdk.infrastructure.toMultiValue

open class VehicleApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://setup.platon.sk/api")
        }
    }

    /**
     * POST /vehicle/events
     * Create vehicle event without receipt image
     * 
     * @param createVehicleEventRequest Vehicle event create payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createVehicleEvent(createVehicleEventRequest: CreateVehicleEventRequest) : CreateDnsRecord200Response {
        val localVarResponse = createVehicleEventWithHttpInfo(createVehicleEventRequest = createVehicleEventRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /vehicle/events
     * Create vehicle event without receipt image
     * 
     * @param createVehicleEventRequest Vehicle event create payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createVehicleEventWithHttpInfo(createVehicleEventRequest: CreateVehicleEventRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = createVehicleEventRequestConfig(createVehicleEventRequest = createVehicleEventRequest)

        return request<CreateVehicleEventRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createVehicleEvent
     *
     * @param createVehicleEventRequest Vehicle event create payload
     * @return RequestConfig
     */
    fun createVehicleEventRequestConfig(createVehicleEventRequest: CreateVehicleEventRequest) : RequestConfig<CreateVehicleEventRequest> {
        val localVariableBody = createVehicleEventRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/vehicle/events",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /vehicle/events/{eventId}
     * Delete vehicle event
     * 
     * @param eventId Vehicle event ID
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteVehicleEvent(eventId: kotlin.Int) : CreateDnsRecord200Response {
        val localVarResponse = deleteVehicleEventWithHttpInfo(eventId = eventId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /vehicle/events/{eventId}
     * Delete vehicle event
     * 
     * @param eventId Vehicle event ID
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteVehicleEventWithHttpInfo(eventId: kotlin.Int) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = deleteVehicleEventRequestConfig(eventId = eventId)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteVehicleEvent
     *
     * @param eventId Vehicle event ID
     * @return RequestConfig
     */
    fun deleteVehicleEventRequestConfig(eventId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/vehicle/events/{eventId}".replace("{"+"eventId"+"}", encodeURIComponent(eventId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /vehicle/events/{eventId}/finalize
     * Finalize vehicle event draft
     * 
     * @param eventId Vehicle event ID
     * @param finalizeVehicleEventRequest Vehicle event finalize payload
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun finalizeVehicleEvent(eventId: kotlin.Int, finalizeVehicleEventRequest: FinalizeVehicleEventRequest) : CreateDnsRecord200Response {
        val localVarResponse = finalizeVehicleEventWithHttpInfo(eventId = eventId, finalizeVehicleEventRequest = finalizeVehicleEventRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /vehicle/events/{eventId}/finalize
     * Finalize vehicle event draft
     * 
     * @param eventId Vehicle event ID
     * @param finalizeVehicleEventRequest Vehicle event finalize payload
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun finalizeVehicleEventWithHttpInfo(eventId: kotlin.Int, finalizeVehicleEventRequest: FinalizeVehicleEventRequest) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = finalizeVehicleEventRequestConfig(eventId = eventId, finalizeVehicleEventRequest = finalizeVehicleEventRequest)

        return request<FinalizeVehicleEventRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation finalizeVehicleEvent
     *
     * @param eventId Vehicle event ID
     * @param finalizeVehicleEventRequest Vehicle event finalize payload
     * @return RequestConfig
     */
    fun finalizeVehicleEventRequestConfig(eventId: kotlin.Int, finalizeVehicleEventRequest: FinalizeVehicleEventRequest) : RequestConfig<FinalizeVehicleEventRequest> {
        val localVariableBody = finalizeVehicleEventRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/vehicle/events/{eventId}/finalize".replace("{"+"eventId"+"}", encodeURIComponent(eventId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /vehicle/events/{eventId}
     * Get vehicle event detail
     * 
     * @param eventId Vehicle event ID
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getVehicleEvent(eventId: kotlin.Int) : CreateDnsRecord200Response {
        val localVarResponse = getVehicleEventWithHttpInfo(eventId = eventId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /vehicle/events/{eventId}
     * Get vehicle event detail
     * 
     * @param eventId Vehicle event ID
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getVehicleEventWithHttpInfo(eventId: kotlin.Int) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = getVehicleEventRequestConfig(eventId = eventId)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getVehicleEvent
     *
     * @param eventId Vehicle event ID
     * @return RequestConfig
     */
    fun getVehicleEventRequestConfig(eventId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/vehicle/events/{eventId}".replace("{"+"eventId"+"}", encodeURIComponent(eventId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /vehicle/events/{eventId}/image
     * Get event image or thumbnail
     * 
     * @param eventId Vehicle event ID
     * @param size Image size variant: thumb, thumbnail or small for thumbnail response (optional)
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getVehicleEventImage(eventId: kotlin.Int, size: kotlin.String? = null) : java.io.File {
        val localVarResponse = getVehicleEventImageWithHttpInfo(eventId = eventId, size = size)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /vehicle/events/{eventId}/image
     * Get event image or thumbnail
     * 
     * @param eventId Vehicle event ID
     * @param size Image size variant: thumb, thumbnail or small for thumbnail response (optional)
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getVehicleEventImageWithHttpInfo(eventId: kotlin.Int, size: kotlin.String?) : ApiResponse<java.io.File?> {
        val localVariableConfig = getVehicleEventImageRequestConfig(eventId = eventId, size = size)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getVehicleEventImage
     *
     * @param eventId Vehicle event ID
     * @param size Image size variant: thumb, thumbnail or small for thumbnail response (optional)
     * @return RequestConfig
     */
    fun getVehicleEventImageRequestConfig(eventId: kotlin.Int, size: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/vehicle/events/{eventId}/image".replace("{"+"eventId"+"}", encodeURIComponent(eventId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /vehicle/currencies
     * List currencies for vehicle events
     * 
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listVehicleCurrencies() : CreateDnsRecord200Response {
        val localVarResponse = listVehicleCurrenciesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /vehicle/currencies
     * List currencies for vehicle events
     * 
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listVehicleCurrenciesWithHttpInfo() : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = listVehicleCurrenciesRequestConfig()

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listVehicleCurrencies
     *
     * @return RequestConfig
     */
    fun listVehicleCurrenciesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/vehicle/currencies",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /vehicle/events
     * List vehicle events for the authenticated driver
     * 
     * @param since Return events with event datetime greater than or equal to the provided local datetime (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listVehicleEvents(since: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = listVehicleEventsWithHttpInfo(since = since)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /vehicle/events
     * List vehicle events for the authenticated driver
     * 
     * @param since Return events with event datetime greater than or equal to the provided local datetime (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listVehicleEventsWithHttpInfo(since: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = listVehicleEventsRequestConfig(since = since)

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listVehicleEvents
     *
     * @param since Return events with event datetime greater than or equal to the provided local datetime (optional)
     * @return RequestConfig
     */
    fun listVehicleEventsRequestConfig(since: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (since != null) {
                    put("since", listOf(since.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/vehicle/events",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /vehicle/vehicles
     * List vehicles available to the authenticated driver
     * 
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listVehicleVehicles() : CreateDnsRecord200Response {
        val localVarResponse = listVehicleVehiclesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /vehicle/vehicles
     * List vehicles available to the authenticated driver
     * 
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listVehicleVehiclesWithHttpInfo() : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = listVehicleVehiclesRequestConfig()

        return request<Unit, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listVehicleVehicles
     *
     * @return RequestConfig
     */
    fun listVehicleVehiclesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/vehicle/vehicles",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /vehicle/events/{eventId}/image
     * Replace event image and rescan event data
     * 
     * @param eventId Vehicle event ID
     * @param image 
     * @param timezone  (optional)
     * @param eventType  (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun rescanVehicleEventImage(eventId: kotlin.Int, image: java.io.File, timezone: kotlin.String? = null, eventType: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = rescanVehicleEventImageWithHttpInfo(eventId = eventId, image = image, timezone = timezone, eventType = eventType)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /vehicle/events/{eventId}/image
     * Replace event image and rescan event data
     * 
     * @param eventId Vehicle event ID
     * @param image 
     * @param timezone  (optional)
     * @param eventType  (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun rescanVehicleEventImageWithHttpInfo(eventId: kotlin.Int, image: java.io.File, timezone: kotlin.String?, eventType: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = rescanVehicleEventImageRequestConfig(eventId = eventId, image = image, timezone = timezone, eventType = eventType)

        return request<Map<String, PartConfig<*>>, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation rescanVehicleEventImage
     *
     * @param eventId Vehicle event ID
     * @param image 
     * @param timezone  (optional)
     * @param eventType  (optional)
     * @return RequestConfig
     */
    fun rescanVehicleEventImageRequestConfig(eventId: kotlin.Int, image: java.io.File, timezone: kotlin.String?, eventType: kotlin.String?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "image" to PartConfig(body = image, headers = mutableMapOf()),
            "timezone" to PartConfig(body = timezone, headers = mutableMapOf()),
            "eventType" to PartConfig(body = eventType, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/vehicle/events/{eventId}/image".replace("{"+"eventId"+"}", encodeURIComponent(eventId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /vehicle/preferred-vehicle
     * Set or clear preferred vehicle
     * 
     * @param setPreferredVehicleRequest Preferred vehicle payload (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun setPreferredVehicle(setPreferredVehicleRequest: SetPreferredVehicleRequest? = null) : CreateDnsRecord200Response {
        val localVarResponse = setPreferredVehicleWithHttpInfo(setPreferredVehicleRequest = setPreferredVehicleRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /vehicle/preferred-vehicle
     * Set or clear preferred vehicle
     * 
     * @param setPreferredVehicleRequest Preferred vehicle payload (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun setPreferredVehicleWithHttpInfo(setPreferredVehicleRequest: SetPreferredVehicleRequest?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = setPreferredVehicleRequestConfig(setPreferredVehicleRequest = setPreferredVehicleRequest)

        return request<SetPreferredVehicleRequest, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setPreferredVehicle
     *
     * @param setPreferredVehicleRequest Preferred vehicle payload (optional)
     * @return RequestConfig
     */
    fun setPreferredVehicleRequestConfig(setPreferredVehicleRequest: SetPreferredVehicleRequest?) : RequestConfig<SetPreferredVehicleRequest> {
        val localVariableBody = setPreferredVehicleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/vehicle/preferred-vehicle",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /vehicle/events/receipt-image
     * Upload receipt image and create processing event draft
     * 
     * @param image 
     * @param timezone 
     * @param eventType  (optional)
     * @return CreateDnsRecord200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun uploadVehicleReceiptImage(image: java.io.File, timezone: kotlin.String, eventType: kotlin.String? = null) : CreateDnsRecord200Response {
        val localVarResponse = uploadVehicleReceiptImageWithHttpInfo(image = image, timezone = timezone, eventType = eventType)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateDnsRecord200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /vehicle/events/receipt-image
     * Upload receipt image and create processing event draft
     * 
     * @param image 
     * @param timezone 
     * @param eventType  (optional)
     * @return ApiResponse<CreateDnsRecord200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun uploadVehicleReceiptImageWithHttpInfo(image: java.io.File, timezone: kotlin.String, eventType: kotlin.String?) : ApiResponse<CreateDnsRecord200Response?> {
        val localVariableConfig = uploadVehicleReceiptImageRequestConfig(image = image, timezone = timezone, eventType = eventType)

        return request<Map<String, PartConfig<*>>, CreateDnsRecord200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation uploadVehicleReceiptImage
     *
     * @param image 
     * @param timezone 
     * @param eventType  (optional)
     * @return RequestConfig
     */
    fun uploadVehicleReceiptImageRequestConfig(image: java.io.File, timezone: kotlin.String, eventType: kotlin.String?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "image" to PartConfig(body = image, headers = mutableMapOf()),
            "timezone" to PartConfig(body = timezone, headers = mutableMapOf()),
            "eventType" to PartConfig(body = eventType, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/vehicle/events/receipt-image",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
