/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.AntispamApi
import sk.platon.controlpanel.sdk.models.AddAntispamMaildataRequest
import sk.platon.controlpanel.sdk.models.CheckAntispamMaildataRulesRequest
import sk.platon.controlpanel.sdk.models.CreateAntispamEmailRuleRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response

class AntispamApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AntispamApi
        //val apiInstance = AntispamApi()

        // to test addAntispamMaildata
        should("test addAntispamMaildata") {
            // uncomment below to test addAntispamMaildata
            //val addAntispamMaildataRequest : AddAntispamMaildataRequest =  // AddAntispamMaildataRequest | Maildata payload
            //val result : CreateDnsRecord200Response = apiInstance.addAntispamMaildata(addAntispamMaildataRequest)
            //result shouldBe ("TODO")
        }

        // to test checkAntispamMaildataRules
        should("test checkAntispamMaildataRules") {
            // uncomment below to test checkAntispamMaildataRules
            //val checkAntispamMaildataRulesRequest : CheckAntispamMaildataRulesRequest =  // CheckAntispamMaildataRulesRequest | Maildata payload
            //val result : CreateDnsRecord200Response = apiInstance.checkAntispamMaildataRules(checkAntispamMaildataRulesRequest)
            //result shouldBe ("TODO")
        }

        // to test createAntispamEmailRule
        should("test createAntispamEmailRule") {
            // uncomment below to test createAntispamEmailRule
            //val createAntispamEmailRuleRequest : CreateAntispamEmailRuleRequest =  // CreateAntispamEmailRuleRequest | Antispam email rule payload
            //val result : CreateDnsRecord200Response = apiInstance.createAntispamEmailRule(createAntispamEmailRuleRequest)
            //result shouldBe ("TODO")
        }

    }
}
