/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.AuthApi
import sk.platon.controlpanel.sdk.models.CreateAuthToken200Response

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test createAuthToken
        should("test createAuthToken") {
            // uncomment below to test createAuthToken
            //val result : CreateAuthToken200Response = apiInstance.createAuthToken()
            //result shouldBe ("TODO")
        }

    }
}
