/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.CartApi
import sk.platon.controlpanel.sdk.models.CheckCartCouponRequest
import sk.platon.controlpanel.sdk.models.CreateCartItemRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.UpdateCartItemCountRequest
import sk.platon.controlpanel.sdk.models.UpdateCartItemRequest

class CartApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CartApi
        //val apiInstance = CartApi()

        // to test checkCartCoupon
        should("test checkCartCoupon") {
            // uncomment below to test checkCartCoupon
            //val checkCartCouponRequest : CheckCartCouponRequest =  // CheckCartCouponRequest | Cart coupon check payload
            //val result : CreateDnsRecord200Response = apiInstance.checkCartCoupon(checkCartCouponRequest)
            //result shouldBe ("TODO")
        }

        // to test createCartItem
        should("test createCartItem") {
            // uncomment below to test createCartItem
            //val createCartItemRequest : CreateCartItemRequest =  // CreateCartItemRequest | Cart item add payload
            //val result : CreateDnsRecord200Response = apiInstance.createCartItem(createCartItemRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteCartItem
        should("test deleteCartItem") {
            // uncomment below to test deleteCartItem
            //val cartItemId : kotlin.Int = 56 // kotlin.Int | Cart item ID
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val result : CreateDnsRecord200Response = apiInstance.deleteCartItem(cartItemId, cname)
            //result shouldBe ("TODO")
        }

        // to test getCartBillingAddress
        should("test getCartBillingAddress") {
            // uncomment below to test getCartBillingAddress
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val result : CreateDnsRecord200Response = apiInstance.getCartBillingAddress(cname)
            //result shouldBe ("TODO")
        }

        // to test getCartCoupon
        should("test getCartCoupon") {
            // uncomment below to test getCartCoupon
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val result : CreateDnsRecord200Response = apiInstance.getCartCoupon(cname)
            //result shouldBe ("TODO")
        }

        // to test getCartTotal
        should("test getCartTotal") {
            // uncomment below to test getCartTotal
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val result : CreateDnsRecord200Response = apiInstance.getCartTotal(cname)
            //result shouldBe ("TODO")
        }

        // to test listCartItems
        should("test listCartItems") {
            // uncomment below to test listCartItems
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val lang : kotlin.String = lang_example // kotlin.String | Response language
            //val result : CreateDnsRecord200Response = apiInstance.listCartItems(cname, lang)
            //result shouldBe ("TODO")
        }

        // to test updateCartItem
        should("test updateCartItem") {
            // uncomment below to test updateCartItem
            //val cartItemId : kotlin.Int = 56 // kotlin.Int | Cart item ID
            //val updateCartItemRequest : UpdateCartItemRequest =  // UpdateCartItemRequest | Cart item update payload
            //val result : CreateDnsRecord200Response = apiInstance.updateCartItem(cartItemId, updateCartItemRequest)
            //result shouldBe ("TODO")
        }

        // to test updateCartItemCount
        should("test updateCartItemCount") {
            // uncomment below to test updateCartItemCount
            //val updateCartItemCountRequest : UpdateCartItemCountRequest =  // UpdateCartItemCountRequest | Cart item count update payload
            //val result : CreateDnsRecord200Response = apiInstance.updateCartItemCount(updateCartItemCountRequest)
            //result shouldBe ("TODO")
        }

    }
}
