/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.DNSApi
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.CreateDnsRecordRequest
import sk.platon.controlpanel.sdk.models.GetDnsRecords200Response
import sk.platon.controlpanel.sdk.models.UpdateDnsRecordRequest

class DNSApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DNSApi
        //val apiInstance = DNSApi()

        // to test createDnsRecord
        should("test createDnsRecord") {
            // uncomment below to test createDnsRecord
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val createDnsRecordRequest : CreateDnsRecordRequest =  // CreateDnsRecordRequest | DNS record payload
            //val result : CreateDnsRecord200Response = apiInstance.createDnsRecord(domain, createDnsRecordRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteDnsRecord
        should("test deleteDnsRecord") {
            // uncomment below to test deleteDnsRecord
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val recordId : kotlin.Int = 56 // kotlin.Int | Record ID
            //val result : CreateDnsRecord200Response = apiInstance.deleteDnsRecord(domain, recordId)
            //result shouldBe ("TODO")
        }

        // to test getDnsRecords
        should("test getDnsRecords") {
            // uncomment below to test getDnsRecords
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val type : kotlin.String = type_example // kotlin.String | Filter records by type
            //val result : GetDnsRecords200Response = apiInstance.getDnsRecords(domain, type)
            //result shouldBe ("TODO")
        }

        // to test updateDnsRecord
        should("test updateDnsRecord") {
            // uncomment below to test updateDnsRecord
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val recordId : kotlin.Int = 56 // kotlin.Int | Record ID
            //val updateDnsRecordRequest : UpdateDnsRecordRequest =  // UpdateDnsRecordRequest | Partial DNS record payload
            //val result : CreateDnsRecord200Response = apiInstance.updateDnsRecord(domain, recordId, updateDnsRecordRequest)
            //result shouldBe ("TODO")
        }

    }
}
