/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.DomainApi
import sk.platon.controlpanel.sdk.models.ChangeDomainNameserversRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.ListDomains200Response
import sk.platon.controlpanel.sdk.models.RegisterDomainRequest
import sk.platon.controlpanel.sdk.models.RenewDomainRequest

class DomainApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DomainApi
        //val apiInstance = DomainApi()

        // to test changeDomainNameservers
        should("test changeDomainNameservers") {
            // uncomment below to test changeDomainNameservers
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val changeDomainNameserversRequest : ChangeDomainNameserversRequest =  // ChangeDomainNameserversRequest | Nameserver payload
            //val result : CreateDnsRecord200Response = apiInstance.changeDomainNameservers(domain, changeDomainNameserversRequest)
            //result shouldBe ("TODO")
        }

        // to test closeDomain
        should("test closeDomain") {
            // uncomment below to test closeDomain
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val result : CreateDnsRecord200Response = apiInstance.closeDomain(domain, cname)
            //result shouldBe ("TODO")
        }

        // to test getDomainInfo
        should("test getDomainInfo") {
            // uncomment below to test getDomainInfo
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name for product context
            //val result : CreateDnsRecord200Response = apiInstance.getDomainInfo(domain, cname)
            //result shouldBe ("TODO")
        }

        // to test listDomains
        should("test listDomains") {
            // uncomment below to test listDomains
            //val cname : kotlin.String = cname_example // kotlin.String | Customer name
            //val result : ListDomains200Response = apiInstance.listDomains(cname)
            //result shouldBe ("TODO")
        }

        // to test registerDomain
        should("test registerDomain") {
            // uncomment below to test registerDomain
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val registerDomainRequest : RegisterDomainRequest =  // RegisterDomainRequest | Domain registration payload
            //val result : CreateDnsRecord200Response = apiInstance.registerDomain(domain, registerDomainRequest)
            //result shouldBe ("TODO")
        }

        // to test renewDomain
        should("test renewDomain") {
            // uncomment below to test renewDomain
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val renewDomainRequest : RenewDomainRequest =  // RenewDomainRequest | Domain renewal payload
            //val result : CreateDnsRecord200Response = apiInstance.renewDomain(domain, renewDomainRequest)
            //result shouldBe ("TODO")
        }

    }
}
