/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.EmailApi
import sk.platon.controlpanel.sdk.models.ChangeMailboxPasswordRequest
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.CreateMailboxRequest

class EmailApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmailApi
        //val apiInstance = EmailApi()

        // to test changeMailboxPassword
        should("test changeMailboxPassword") {
            // uncomment below to test changeMailboxPassword
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val username : kotlin.String = username_example // kotlin.String | Mailbox username
            //val changeMailboxPasswordRequest : ChangeMailboxPasswordRequest =  // ChangeMailboxPasswordRequest | Mailbox password payload
            //val result : CreateDnsRecord200Response = apiInstance.changeMailboxPassword(domain, username, changeMailboxPasswordRequest)
            //result shouldBe ("TODO")
        }

        // to test createMailbox
        should("test createMailbox") {
            // uncomment below to test createMailbox
            //val domain : kotlin.String = domain_example // kotlin.String | Domain name
            //val createMailboxRequest : CreateMailboxRequest =  // CreateMailboxRequest | Mailbox payload
            //val result : CreateDnsRecord200Response = apiInstance.createMailbox(domain, createMailboxRequest)
            //result shouldBe ("TODO")
        }

    }
}
