/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.LLMApi
import sk.platon.controlpanel.sdk.models.SpamDetection200Response
import sk.platon.controlpanel.sdk.models.SpamDetectionRequest

class LLMApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LLMApi
        //val apiInstance = LLMApi()

        // to test spamDetection
        should("test spamDetection") {
            // uncomment below to test spamDetection
            //val spamDetectionRequest : SpamDetectionRequest =  // SpamDetectionRequest | Spam detection payload
            //val result : SpamDetection200Response = apiInstance.spamDetection(spamDetectionRequest)
            //result shouldBe ("TODO")
        }

    }
}
