/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.OAuthApi
import sk.platon.controlpanel.sdk.models.CreateOauthRequest200Response
import sk.platon.controlpanel.sdk.models.CreateOauthRequestRequest
import sk.platon.controlpanel.sdk.models.DeleteOauthToken200Response
import sk.platon.controlpanel.sdk.models.GetOauthScopes200Response
import sk.platon.controlpanel.sdk.models.RefreshOauthTokenRequest
import sk.platon.controlpanel.sdk.models.VerifyOauthRequest200Response

class OAuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OAuthApi
        //val apiInstance = OAuthApi()

        // to test createOauthRequest
        should("test createOauthRequest") {
            // uncomment below to test createOauthRequest
            //val createOauthRequestRequest : CreateOauthRequestRequest =  // CreateOauthRequestRequest | OAuth create payload
            //val result : CreateOauthRequest200Response = apiInstance.createOauthRequest(createOauthRequestRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteOauthToken
        should("test deleteOauthToken") {
            // uncomment below to test deleteOauthToken
            //val token : kotlin.String = token_example // kotlin.String | OAuth token
            //val result : DeleteOauthToken200Response = apiInstance.deleteOauthToken(token)
            //result shouldBe ("TODO")
        }

        // to test getOauthScopes
        should("test getOauthScopes") {
            // uncomment below to test getOauthScopes
            //val result : GetOauthScopes200Response = apiInstance.getOauthScopes()
            //result shouldBe ("TODO")
        }

        // to test refreshOauthToken
        should("test refreshOauthToken") {
            // uncomment below to test refreshOauthToken
            //val refreshOauthTokenRequest : RefreshOauthTokenRequest =  // RefreshOauthTokenRequest | OAuth refresh payload
            //val result : VerifyOauthRequest200Response = apiInstance.refreshOauthToken(refreshOauthTokenRequest)
            //result shouldBe ("TODO")
        }

        // to test verifyOauthRequest
        should("test verifyOauthRequest") {
            // uncomment below to test verifyOauthRequest
            //val verifyToken : kotlin.String = verifyToken_example // kotlin.String | Verify token from OAuth create response
            //val result : VerifyOauthRequest200Response = apiInstance.verifyOauthRequest(verifyToken)
            //result shouldBe ("TODO")
        }

    }
}
