/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.SystemApi
import sk.platon.controlpanel.sdk.models.Hello200Response
import sk.platon.controlpanel.sdk.models.Revision200Response
import sk.platon.controlpanel.sdk.models.Time200Response

class SystemApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemApi
        //val apiInstance = SystemApi()

        // to test hello
        should("test hello") {
            // uncomment below to test hello
            //val result : Hello200Response = apiInstance.hello()
            //result shouldBe ("TODO")
        }

        // to test revision
        should("test revision") {
            // uncomment below to test revision
            //val result : Revision200Response = apiInstance.revision()
            //result shouldBe ("TODO")
        }

        // to test time
        should("test time") {
            // uncomment below to test time
            //val result : Time200Response = apiInstance.time()
            //result shouldBe ("TODO")
        }

    }
}
