/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import sk.platon.controlpanel.sdk.apis.VehicleApi
import sk.platon.controlpanel.sdk.models.CreateDnsRecord200Response
import sk.platon.controlpanel.sdk.models.CreateVehicleEventRequest
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequest
import sk.platon.controlpanel.sdk.models.SetPreferredVehicleRequest

class VehicleApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VehicleApi
        //val apiInstance = VehicleApi()

        // to test createVehicleEvent
        should("test createVehicleEvent") {
            // uncomment below to test createVehicleEvent
            //val createVehicleEventRequest : CreateVehicleEventRequest =  // CreateVehicleEventRequest | Vehicle event create payload
            //val result : CreateDnsRecord200Response = apiInstance.createVehicleEvent(createVehicleEventRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteVehicleEvent
        should("test deleteVehicleEvent") {
            // uncomment below to test deleteVehicleEvent
            //val eventId : kotlin.Int = 56 // kotlin.Int | Vehicle event ID
            //val result : CreateDnsRecord200Response = apiInstance.deleteVehicleEvent(eventId)
            //result shouldBe ("TODO")
        }

        // to test finalizeVehicleEvent
        should("test finalizeVehicleEvent") {
            // uncomment below to test finalizeVehicleEvent
            //val eventId : kotlin.Int = 56 // kotlin.Int | Vehicle event ID
            //val finalizeVehicleEventRequest : FinalizeVehicleEventRequest =  // FinalizeVehicleEventRequest | Vehicle event finalize payload
            //val result : CreateDnsRecord200Response = apiInstance.finalizeVehicleEvent(eventId, finalizeVehicleEventRequest)
            //result shouldBe ("TODO")
        }

        // to test getVehicleEvent
        should("test getVehicleEvent") {
            // uncomment below to test getVehicleEvent
            //val eventId : kotlin.Int = 56 // kotlin.Int | Vehicle event ID
            //val result : CreateDnsRecord200Response = apiInstance.getVehicleEvent(eventId)
            //result shouldBe ("TODO")
        }

        // to test getVehicleEventImage
        should("test getVehicleEventImage") {
            // uncomment below to test getVehicleEventImage
            //val eventId : kotlin.Int = 56 // kotlin.Int | Vehicle event ID
            //val size : kotlin.String = size_example // kotlin.String | Image size variant: thumb, thumbnail or small for thumbnail response
            //val result : java.io.File = apiInstance.getVehicleEventImage(eventId, size)
            //result shouldBe ("TODO")
        }

        // to test listVehicleCurrencies
        should("test listVehicleCurrencies") {
            // uncomment below to test listVehicleCurrencies
            //val result : CreateDnsRecord200Response = apiInstance.listVehicleCurrencies()
            //result shouldBe ("TODO")
        }

        // to test listVehicleEvents
        should("test listVehicleEvents") {
            // uncomment below to test listVehicleEvents
            //val since : kotlin.String = since_example // kotlin.String | Return events with event datetime greater than or equal to the provided local datetime
            //val result : CreateDnsRecord200Response = apiInstance.listVehicleEvents(since)
            //result shouldBe ("TODO")
        }

        // to test listVehicleVehicles
        should("test listVehicleVehicles") {
            // uncomment below to test listVehicleVehicles
            //val result : CreateDnsRecord200Response = apiInstance.listVehicleVehicles()
            //result shouldBe ("TODO")
        }

        // to test rescanVehicleEventImage
        should("test rescanVehicleEventImage") {
            // uncomment below to test rescanVehicleEventImage
            //val eventId : kotlin.Int = 56 // kotlin.Int | Vehicle event ID
            //val image : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val timezone : kotlin.String = timezone_example // kotlin.String | 
            //val eventType : kotlin.String = eventType_example // kotlin.String | 
            //val result : CreateDnsRecord200Response = apiInstance.rescanVehicleEventImage(eventId, image, timezone, eventType)
            //result shouldBe ("TODO")
        }

        // to test setPreferredVehicle
        should("test setPreferredVehicle") {
            // uncomment below to test setPreferredVehicle
            //val setPreferredVehicleRequest : SetPreferredVehicleRequest =  // SetPreferredVehicleRequest | Preferred vehicle payload
            //val result : CreateDnsRecord200Response = apiInstance.setPreferredVehicle(setPreferredVehicleRequest)
            //result shouldBe ("TODO")
        }

        // to test uploadVehicleReceiptImage
        should("test uploadVehicleReceiptImage") {
            // uncomment below to test uploadVehicleReceiptImage
            //val image : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val timezone : kotlin.String = timezone_example // kotlin.String | 
            //val eventType : kotlin.String = eventType_example // kotlin.String | 
            //val result : CreateDnsRecord200Response = apiInstance.uploadVehicleReceiptImage(image, timezone, eventType)
            //result shouldBe ("TODO")
        }

    }
}
