/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cname 
 * @param dnsServersOpt 
 * @param ns 
 * @param ns1 
 * @param ns1Ipv4 
 * @param ns1Ipv6 
 * @param ns2 
 * @param ns2Ipv4 
 * @param ns2Ipv6 
 * @param ns3 
 * @param ns3Ipv4 
 * @param ns3Ipv6 
 * @param ns4 
 * @param ns4Ipv4 
 * @param ns4Ipv6 
 */


data class ChangeDomainNameserversRequest (

    @Json(name = "cname")
    val cname: kotlin.String? = null,

    @Json(name = "dns_servers_opt")
    val dnsServersOpt: kotlin.String? = null,

    @Json(name = "ns")
    val ns: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "ns1")
    val ns1: kotlin.String? = null,

    @Json(name = "ns1_ipv4")
    val ns1Ipv4: kotlin.String? = null,

    @Json(name = "ns1_ipv6")
    val ns1Ipv6: kotlin.String? = null,

    @Json(name = "ns2")
    val ns2: kotlin.String? = null,

    @Json(name = "ns2_ipv4")
    val ns2Ipv4: kotlin.String? = null,

    @Json(name = "ns2_ipv6")
    val ns2Ipv6: kotlin.String? = null,

    @Json(name = "ns3")
    val ns3: kotlin.String? = null,

    @Json(name = "ns3_ipv4")
    val ns3Ipv4: kotlin.String? = null,

    @Json(name = "ns3_ipv6")
    val ns3Ipv6: kotlin.String? = null,

    @Json(name = "ns4")
    val ns4: kotlin.String? = null,

    @Json(name = "ns4_ipv4")
    val ns4Ipv4: kotlin.String? = null,

    @Json(name = "ns4_ipv6")
    val ns4Ipv6: kotlin.String? = null

) {


}

