/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appName 
 * @param appUrlHomepage 
 * @param appUrlReturn 
 * @param scopes 
 */


data class CreateOauthRequestRequest (

    @Json(name = "app_name")
    val appName: kotlin.String? = null,

    @Json(name = "app_url_homepage")
    val appUrlHomepage: kotlin.String? = null,

    @Json(name = "app_url_return")
    val appUrlReturn: kotlin.String? = null,

    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>? = null

) {


}

