/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param pattern 
 */


data class CreateAntispamEmailRuleRequest (

    @Json(name = "type")
    val type: CreateAntispamEmailRuleRequest.Type,

    @Json(name = "pattern")
    val pattern: kotlin.String

) {

    /**
     * 
     *
     * Values: sender_email,sender_domain,sender_ip
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "sender_email") sender_email("sender_email"),
        @Json(name = "sender_domain") sender_domain("sender_domain"),
        @Json(name = "sender_ip") sender_ip("sender_ip");
    }

}

