/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tokenType 
 * @param token 
 * @param expiresIn 
 * @param tokenExpire 
 * @param cname 
 * @param scopes 
 */


data class CreateAuthToken200ResponseData (

    @Json(name = "token_type")
    val tokenType: kotlin.String? = null,

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int? = null,

    @Json(name = "token_expire")
    val tokenExpire: kotlin.String? = null,

    @Json(name = "cname")
    val cname: kotlin.String? = null,

    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>? = null

) {


}

