/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productName 
 * @param cname 
 * @param domain 
 * @param itemCount 
 * @param currencyId 
 * @param parameters 
 * @param processType 
 * @param lang 
 */


data class CreateCartItemRequest (

    @Json(name = "product_name")
    val productName: kotlin.String,

    @Json(name = "cname")
    val cname: kotlin.String? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "item_count")
    val itemCount: kotlin.Int? = null,

    @Json(name = "currency_id")
    val currencyId: kotlin.String? = null,

    @Json(name = "parameters")
    val parameters: kotlin.Any? = null,

    @Json(name = "process_type")
    val processType: kotlin.String? = null,

    @Json(name = "lang")
    val lang: kotlin.String? = null

) {


}

