/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param verifyToken 
 * @param accessToken 
 * @param redirectUrl 
 * @param verifyUrl 
 * @param verifyIntervalSeconds 
 */


data class CreateOauthRequest200ResponseData (

    @Json(name = "verify_token")
    val verifyToken: kotlin.String? = null,

    @Json(name = "access_token")
    val accessToken: kotlin.String? = null,

    @Json(name = "redirect_url")
    val redirectUrl: kotlin.String? = null,

    @Json(name = "verify_url")
    val verifyUrl: kotlin.String? = null,

    @Json(name = "verify_interval_seconds")
    val verifyIntervalSeconds: kotlin.Int? = null

) {


}

