/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fuelingNo 
 * @param fuelType 
 * @param volume 
 * @param unit 
 */


data class FinalizeVehicleEventRequestFueling (

    @Json(name = "fuelingNo")
    val fuelingNo: kotlin.Int? = null,

    @Json(name = "fuelType")
    val fuelType: kotlin.String? = null,

    @Json(name = "volume")
    val volume: java.math.BigDecimal? = null,

    @Json(name = "unit")
    val unit: kotlin.String? = null

) {


}

