/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param addressText 
 * @param lat 
 * @param lon 
 * @param placeName 
 */


data class FinalizeVehicleEventRequestLocation (

    @Json(name = "addressText")
    val addressText: kotlin.String,

    @Json(name = "lat")
    val lat: java.math.BigDecimal,

    @Json(name = "lon")
    val lon: java.math.BigDecimal,

    @Json(name = "placeName")
    val placeName: kotlin.String? = null

) {


}

