/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestFueling
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestLocation
import sk.platon.controlpanel.sdk.models.FinalizeVehicleEventRequestMoney

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventType 
 * @param datetimeLocal 
 * @param timezone 
 * @param location 
 * @param purpose 
 * @param notes 
 * @param odometer 
 * @param money 
 * @param fueling 
 */


data class FinalizeVehicleEventRequest (

    @Json(name = "eventType")
    val eventType: kotlin.String,

    @Json(name = "datetimeLocal")
    val datetimeLocal: kotlin.String,

    @Json(name = "timezone")
    val timezone: kotlin.String,

    @Json(name = "location")
    val location: FinalizeVehicleEventRequestLocation,

    @Json(name = "purpose")
    val purpose: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "odometer")
    val odometer: kotlin.Int? = null,

    @Json(name = "money")
    val money: FinalizeVehicleEventRequestMoney? = null,

    @Json(name = "fueling")
    val fueling: FinalizeVehicleEventRequestFueling? = null

) {


}

