/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import sk.platon.controlpanel.sdk.models.GetDnsRecords200ResponseDataRecordsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param domainId 
 * @param domain 
 * @param master 
 * @param type 
 * @param records 
 */


data class GetDnsRecords200ResponseData (

    @Json(name = "domain_id")
    val domainId: kotlin.Int? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "master")
    val master: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "records")
    val records: kotlin.collections.List<GetDnsRecords200ResponseDataRecordsInner>? = null

) {


}

