/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param merged 
 * @param fromCname 
 * @param toCname 
 * @param movedItems 
 * @param mergedItems 
 * @param itemsCount 
 */


data class MergeCartItems200ResponseData (

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "merged")
    val merged: kotlin.Boolean? = null,

    @Json(name = "from_cname")
    val fromCname: kotlin.String? = null,

    @Json(name = "to_cname")
    val toCname: kotlin.String? = null,

    @Json(name = "moved_items")
    val movedItems: kotlin.Int? = null,

    @Json(name = "merged_items")
    val mergedItems: kotlin.Int? = null,

    @Json(name = "items_count")
    val itemsCount: kotlin.Int? = null

) {


}

