/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import sk.platon.controlpanel.sdk.models.Revision200ResponseData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param retval 
 * @param msg 
 * @param `data` 
 * @param requestId 
 */


data class Revision200Response (

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "retval")
    val retval: kotlin.Int,

    @Json(name = "msg")
    val msg: kotlin.String,

    @Json(name = "data")
    val `data`: Revision200ResponseData,

    @Json(name = "requestId")
    val requestId: kotlin.Int

) {


}

