/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param classification Normalized classification returned by the LLM.
 * @param confidence Normalized confidence from 0 to 100.
 * @param reason Short explanation in Slovak.
 * @param signals Most important signals used for the classification.
 * @param error True when the LLM call or response validation failed.
 * @param errorMessage Short technical error reason. Raw LLM response is never returned here.
 */


data class SpamDetection200ResponseData (

    /* Normalized classification returned by the LLM. */
    @Json(name = "classification")
    val classification: SpamDetection200ResponseData.Classification,

    /* Normalized confidence from 0 to 100. */
    @Json(name = "confidence")
    val confidence: java.math.BigDecimal,

    /* Short explanation in Slovak. */
    @Json(name = "reason")
    val reason: kotlin.String,

    /* Most important signals used for the classification. */
    @Json(name = "signals")
    val signals: kotlin.collections.List<kotlin.String>,

    /* True when the LLM call or response validation failed. */
    @Json(name = "error")
    val error: kotlin.Boolean,

    /* Short technical error reason. Raw LLM response is never returned here. */
    @Json(name = "error_message")
    val errorMessage: kotlin.String

) {

    /**
     * Normalized classification returned by the LLM.
     *
     * Values: spam,ham,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Classification(val value: kotlin.String) {
        @Json(name = "spam") spam("spam"),
        @Json(name = "ham") ham("ham"),
        @Json(name = "unknown") unknown("unknown");
    }

}

