/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productName 
 * @param domain 
 * @param count 
 * @param cname 
 */


data class UpdateCartItemCountRequest (

    @Json(name = "product_name")
    val productName: kotlin.String,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "cname")
    val cname: kotlin.String? = null

) {


}

