/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productName 
 * @param productDetail 
 * @param itemCount 
 * @param price 
 * @param productPrice 
 */


data class UpdateCartItemRequestData (

    @Json(name = "product_name")
    val productName: kotlin.String? = null,

    @Json(name = "product_detail")
    val productDetail: kotlin.String? = null,

    @Json(name = "item_count")
    val itemCount: kotlin.Int? = null,

    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    @Json(name = "product_price")
    val productPrice: java.math.BigDecimal? = null

) {


}

