/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package sk.platon.controlpanel.sdk.models

import sk.platon.controlpanel.sdk.models.WhoisDomain200ResponseDataRetval

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param domain 
 * @param isFree 
 * @param isPremium 
 * @param result 
 * @param retval 
 * @param prices 
 */


data class WhoisDomain200ResponseData (

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "isFree")
    val isFree: kotlin.Boolean? = null,

    @Json(name = "isPremium")
    val isPremium: kotlin.Boolean? = null,

    @Json(name = "result")
    val result: kotlin.Int? = null,

    @Json(name = "retval")
    val retval: WhoisDomain200ResponseDataRetval? = null,

    @Json(name = "prices")
    val prices: kotlin.Any? = null

) {


}

